PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE [b] (
   [id] TEXT
);
INSERT INTO b VALUES('b1');
INSERT INTO b VALUES('b2');
INSERT INTO b VALUES('b3');
CREATE TABLE [a] (
   [id] TEXT
);
INSERT INTO a VALUES('a1');
INSERT INTO a VALUES('a2');
INSERT INTO a VALUES('a3');
CREATE TABLE c(
id text NOT NULL
);
INSERT INTO c VALUES('a1');
INSERT INTO c VALUES('b1');
COMMIT;
